# Generated by Django 4.1.7 on 2023-02-28 08:22

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.CharField(db_column='flight_number', max_length=150)),
                ('origin_country', models.CharField(db_column='origin_country', max_length=256)),
                ('origin_city', models.CharField(db_column='origin_city', max_length=256)),
                ('origin_airport_code', models.CharField(blank=True, db_column='origin_airport_code', max_length=256, null=True)),
                ('destination_country', models.CharField(db_column='destination_country', max_length=256)),
                ('destination_city', models.CharField(db_column='destination_cityy', max_length=256)),
                ('destination_airport_code', models.CharField(blank=True, db_column='destination_airport_code', max_length=256, null=True)),
                ('date_time_origin', models.DateTimeField(db_column='date_time_origin')),
                ('date_time_destination', models.DateTimeField(db_column='date_time_destination')),
                ('total_num_of_seats', models.IntegerField(db_column='total_num_of_seats')),
                ('seats_left', models.IntegerField(db_column='seats_left')),
                ('is_cancelled', models.BooleanField(blank=True, db_column='is_cancelled', default=False, null=True)),
                ('price', models.IntegerField(db_column='price')),
            ],
            options={
                'db_table': 'flights',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_seats', models.IntegerField(db_column='number_of_seats', validators=[django.core.validators.MinValueValidator(0)])),
                ('order_date', models.DateTimeField(db_column='order_date')),
                ('total_price', models.IntegerField(db_column='total_price')),
                ('flight_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='airplain_app.flight')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'orders',
            },
        ),
    ]
